var Refrigrator = "Dowlance";
var Age = 25;
var numbers = [2, 4, 6, 8, 10];
console.log("Is Refrigrator == 'Dowlance' I predict True");
console.log(Refrigrator == 'Dowlance');
console.log("Is Refrigrator == 'Hier' I predict False");
console.log(Refrigrator == 'Hier');
console.log("Ise Age == 25 I predict True");
console.log(Age == 25);
console.log("Is Age != 25 I Predict False");
console.log(Age != 25);
console.log("2 in numbers I predict True");
console.log(2 in numbers);
console.log("Is 5 in numbers I predict False");
console.log(5 in numbers);
